// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team.Infrastructure.DbContext;

namespace Team.Infrastructure.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Team.Model.Model.ParentModel.Children", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account");

                    b.Property<string>("Name");

                    b.Property<int>("ParentId");

                    b.Property<int>("RelationShip");

                    b.Property<int>("SonId");

                    b.HasKey("Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunApplicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApplicationDate");

                    b.Property<string>("Name");

                    b.Property<int>("RunTeamId");

                    b.Property<int>("Sex");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RunTeamId");

                    b.ToTable("RunApplicants");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunParticipants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApplicationDate");

                    b.Property<string>("Name");

                    b.Property<int>("RunTeamId");

                    b.Property<int>("Sex");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RunTeamId");

                    b.ToTable("RunParticipantses");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationStatus");

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("Introduction");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RunTeams");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTeamRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Calories");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("date");

                    b.Property<float>("Distance");

                    b.Property<int>("RunTeamId");

                    b.HasKey("Id");

                    b.HasIndex("RunTeamId");

                    b.ToTable("RunTeamRecords");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTeamWeekChartBuffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Distance");

                    b.Property<string>("Introduction");

                    b.Property<int>("RunTeamId");

                    b.Property<string>("TeamName");

                    b.HasKey("Id");

                    b.HasIndex("RunTeamId");

                    b.ToTable("RunTeamWeekChartBuffers");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTimeDailyCharts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Distance");

                    b.Property<string>("Introduction");

                    b.Property<int>("Ranking");

                    b.Property<int>("RunTeamId");

                    b.Property<string>("TeamName");

                    b.HasKey("Id");

                    b.HasIndex("RunTeamId");

                    b.ToTable("RunTimeDailyChartses");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTimeWeekCharts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Distance");

                    b.Property<string>("Introduction");

                    b.Property<int>("Ranking");

                    b.Property<int>("RunTeamId");

                    b.Property<string>("TeamName");

                    b.HasKey("Id");

                    b.HasIndex("RunTeamId");

                    b.ToTable("RunTimeWeekChartses");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.TeamList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("Introduction");

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TeamLists");
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Participants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sex");

                    b.Property<int>("TeamId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Participantses");
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Calories");

                    b.Property<float>("Distance");

                    b.Property<string>("EndPlace")
                        .IsRequired();

                    b.Property<DateTime>("EndTime");

                    b.Property<float>("Speed");

                    b.Property<int>("SportFreeModel");

                    b.Property<string>("StarPlace")
                        .IsRequired();

                    b.Property<DateTime>("StarTime");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Statistical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AllTime");

                    b.Property<float>("Calories");

                    b.Property<float>("Distance");

                    b.Property<int>("SportFreeModel");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Statisticals");
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<DateTime>("AgreedTime");

                    b.Property<int>("AllCount");

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("Introduction");

                    b.Property<string>("Name");

                    b.Property<int>("Sport");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Team.Model.Model.UserModel.LatitudeAndLongitude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommunicationId");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LatitudeAndLongitudes");
                });

            modelBuilder.Entity("Team.Model.Model.UserModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("Province");

                    b.Property<int>("Role");

                    b.Property<int>("RunTeamId");

                    b.Property<int>("Sex");

                    b.Property<string>("StudentId");

                    b.Property<int>("UniversityId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunApplicant", b =>
                {
                    b.HasOne("Team.Model.Model.RunTeamModel.RunTeam", "RunTeam")
                        .WithMany("RunApplicants")
                        .HasForeignKey("RunTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunParticipants", b =>
                {
                    b.HasOne("Team.Model.Model.RunTeamModel.RunTeam", "RunTeam")
                        .WithMany("RunParticipantses")
                        .HasForeignKey("RunTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTeam", b =>
                {
                    b.HasOne("Team.Model.Model.UserModel.User", "User")
                        .WithOne("RunTeam")
                        .HasForeignKey("Team.Model.Model.RunTeamModel.RunTeam", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTeamRecord", b =>
                {
                    b.HasOne("Team.Model.Model.RunTeamModel.RunTeam", "RunTeam")
                        .WithMany("RunTeamRecords")
                        .HasForeignKey("RunTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTeamWeekChartBuffer", b =>
                {
                    b.HasOne("Team.Model.Model.RunTeamModel.RunTeam", "RunTeam")
                        .WithMany()
                        .HasForeignKey("RunTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTimeDailyCharts", b =>
                {
                    b.HasOne("Team.Model.Model.RunTeamModel.RunTeam", "RunTeam")
                        .WithMany()
                        .HasForeignKey("RunTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.RunTimeWeekCharts", b =>
                {
                    b.HasOne("Team.Model.Model.RunTeamModel.RunTeam", "RunTeam")
                        .WithMany()
                        .HasForeignKey("RunTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.RunTeamModel.TeamList", b =>
                {
                    b.HasOne("Team.Model.Model.UserModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Participants", b =>
                {
                    b.HasOne("Team.Model.Model.TeamModel.Team", "Team")
                        .WithMany("Participantses")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Run", b =>
                {
                    b.HasOne("Team.Model.Model.UserModel.User", "User")
                        .WithMany("Runs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Statistical", b =>
                {
                    b.HasOne("Team.Model.Model.UserModel.User", "User")
                        .WithMany("Statistical")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.TeamModel.Team", b =>
                {
                    b.HasOne("Team.Model.Model.UserModel.User", "User")
                        .WithMany("Teams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team.Model.Model.UserModel.LatitudeAndLongitude", b =>
                {
                    b.HasOne("Team.Model.Model.UserModel.User", "User")
                        .WithOne("LatitudeAndLongitude")
                        .HasForeignKey("Team.Model.Model.UserModel.LatitudeAndLongitude", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
